/*
 * generated by Xtext 2.21.0
 */
package org.agileware.natural.cucumber.ui;

import org.agileware.natural.cucumber.ui.syntaxcoloring.HighlightingConfiguration;
import org.agileware.natural.cucumber.ui.syntaxcoloring.SemanticHighlightingCalculator;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CucumberUiModule extends AbstractCucumberUiModule {

	public CucumberUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return HighlightingConfiguration.class;
	}

	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
		return SemanticHighlightingCalculator.class;
	}
}
