/*
 * generated by Xtext 2.21.0
 */
package org.agileware.natural.jbehave.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class JbehaveUiModule extends AbstractJbehaveUiModule {

	public JbehaveUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
