/*
 * generated by Xtext 2.21.0
 */
package org.agileware.natural.cucumber.ui.outline;

import org.agileware.natural.cucumber.cucumber.CucumberModel;
import org.agileware.natural.cucumber.cucumber.Step;
import org.agileware.natural.cucumber.cucumber.Table;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.eclipse.xtext.ui.editor.outline.impl.DocumentRootNode;

/**
 * Customization of the default outline structure.
 *
 * See
 * https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class CucumberOutlineTreeProvider extends DefaultOutlineTreeProvider {

	/**
	 * Skip creation of the root model.
	 * 
	 * @param parentNode
	 * @param model
	 */
	protected void _createChildren(DocumentRootNode parentNode, CucumberModel model) {
		if (model.getFeature() != null) {
			createNode(parentNode, model);
		}
	}

	/**
	 * Do not allow expansion of table nodes
	 * 
	 * @param model
	 * @return
	 */
	protected boolean _isLeaf(Table model) {
		return true;
	}

	/**
	 * Only allow expansion of step nodes with tables
	 * 
	 * @param model
	 * @return
	 */
	protected boolean _isLeaf(Step model) {
		return model.getTable() == null && model.getCode() == null;
	}
}
