/*
 * generated by Xtext 2.21.0
 */
package org.agileware.natural.cucumber;

import org.agileware.natural.core.stepmatcher.DefaultAnnotationDescriptor;
import org.agileware.natural.core.stepmatcher.DefaultStepMatcher;
import org.agileware.natural.core.stepmatcher.IAnnotationDescriptor;
import org.agileware.natural.core.stepmatcher.IStepMatcher;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CucumberRuntimeModule extends AbstractCucumberRuntimeModule {
	
	public Class<? extends IAnnotationDescriptor> bindAnnotationDescriptor() {
		return DefaultAnnotationDescriptor.class;
	}
	
	public Class<? extends IStepMatcher> bindStepMatcher() {
		return DefaultStepMatcher.class;
	}
}
