/*
 * generated by Xtext
 */
package org.agileware.natural.cucumber;

import org.agileware.natural.common.stepmatcher.DefaultStepMatcher;
import org.agileware.natural.common.stepmatcher.IStepMatcher;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CucumberRuntimeModule extends AbstractCucumberRuntimeModule {
	
	/**
	 * @return
	 */
	public Class<? extends IStepMatcher> bindStepMatcher() {
		return DefaultStepMatcher.class;
	}
	
}
