/*
 * generated by Xtext 2.21.0
 */
package org.agileware.natural.cucumber;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CucumberStandaloneSetup extends CucumberStandaloneSetupGenerated {

	public static void doSetup() {
		new CucumberStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
